#' logfile_data
#'
#' Description
#'
#' @docType data
#' @keywords datasets
#' @name logfile_data
#' @description logfile_data is a dataset that was saved as a .csv file after reading .txt files, otherwise known as logfiles, generated by the mobile application "WayTO" into R. This dataset was obtained through a two-month experiment undertaken by the Spatial Intelligence Lab at the University of Münster.
#' @usage data(logfile_data)
#' @format The logfile_data data frame has 3137 rows and 10 columns on map interactions at various points in time.
#' @details ID Unique ID given to each participant that makes up the file name for each logfile. Each ID contains a number and a letter. The number corresponds with the order of participants, and the letter corresponds to
#' 1. The researcher (a/b - Researcher 1; w/wo - Researcher 2) and
#' 2. The viewability of off-screen markers (a/w = with on-screen markers, b/wo = without off-screen markers)
#' @details Action Which interaction occurred at that time interval? Map moved to position, Clicked on marker, Clicked on map
#' @details Landmark Which Landmark was clicked on? Wasserturm, Zoo, Netto, WL Bank, Fussballstadion, Innenstadt, Hbf
#' @details Time The time of the observation, in the form of Tue Jun 16 10:11:53 GMT+02:00 2015
#' @details Zoom The zoom level of the observation, in the form of e.g. 14.96016
#' @details Lat The latitude where the observation took place, e.g. 51.94721
#' @details Lon The longitude where the observation took place, e.g. 7.621254
#' @details Zoomed Displays TRUE or FALSE, depending if there was a difference between the previous and current zoom value
#' @details Panned Displays TRUE or FALSE, depending if there was a difference between the previous and current latitude and longitude values.
#' @details WithOffScreenMarkers Displays TRUE or FALSE, depending on the corresponding letters in the ID, e.g. 5w is TRUE for WithOnScreenMarkers
#' @examples
#' ## load data
#' # data(logfile_data)
#' x <- as.numeric(logfile_data$Zoom, ID="3w")
#' x <- head(x, 50)
#' mean(x)

NULL
